### ISSUE TITLE
[integration testing] Is this NervesTime.Ntpd unexpected :EXIT . . "expected" ?

### ISSUE THREAD

**Issue by jsimmonds2** [nerves-time/nerves_time_rtc_ds3231#1]
Testing what I think is working code using plain **nerves_system_rpi4** `1.10.2` and see the Logger messages in the screenshot below.

**NervesTime.RTC.DS3231.get_time/1** continues to work and return correct Naive Time.

Picture this :)

![image](https://user-images.githubusercontent.com/1224439/75740876-ff4f8f80-5d5c-11ea-8d4a-d3c2a3cd5bf1.png)

**Comment by fhunleth** [comment]
Your code is fine. That's a bug in mine. I made some code pickier on exits and missed marking that one as expected. I'll fix soon! Thanks for letting me know.

**Comment by fhunleth** [comment]
Fixed in https://github.com/nerves-time/nerves_time/commit/bae03e01cf1bd717ab089f3e7baea7ec42e97edc. Thanks again!
